version: "3"

services:
  client:
    build:
      context: ./client
    container_name: client
    ports:
      - "80:80"
    depends_on:
      - server
  server:
    build:
      context: ./server
    container_name: server
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=pass123
